export const barbarianQuotes = [
  'Crush your bugs, see them driven before you, and hear the lamentations of their functions!',
  'The code is strong, but flesh is stronger!',
  "If you find yourself alone, coding in green fields with the sun on your face, do not be troubled. For you are in the Stillmist, and you're already dead!",
  'Code, compile, and conquer!',
  'I live, I code, I commit... and I am content.',
  'What is best in programming? To crush the bugs, to see them driven from your code, and to hear the celebration of your users!',
  'Let me tell you of the days of high adventure... in coding!',
  'Huge knows that a man is made of steel... and bugs, of willingness and git blame.',
  'Between the time when the Blood Mist drank the villages, and the rise of the sons of Alderland, there was an age undreamed of. And onto this, LineLord, destined to track all code in your repository!',
  'Everyone has the power to code. Not everyone has the courage to use it wisely.',
  'By Huge! Your code shall echo through the servers for all eternity!',
  'What good is a compiler that cannot crush? What good is a framework that cannot bend steel?',
  'The app closes, but your legend lives on in the logs!',
  'To the hellish depths with runtime errors! Victory belongs to the debugger!',
  'I have known many gods. Git has forgotten more than all the others combined.',
  'The stars are not aligned for coding tonight. Close your IDE and rest, warrior.',
  'A database without queries is like a sword without a blade - useless!',
  'Trust no framework you cannot debug with your own hands.',
  'The app may end, but the repository is eternal!',
  'Your commits have been weighed, your pushes measured... and you have not been found wanting.',
  'In the name of Huge! Your code compiles without warning!',
  'The wheel of debugging turns, and ages come and pass, leaving memories that become legend.',
  'When I commit my final push, I want to go out like a warrior - the code bent to my will, the conflicts silenced by force!',
  'Contemplate this upon the Tree of Woe: merge conflicts are temporary, but git history is forever.',
  'What is steel compared to the code that wields it? What is the compiler compared to the mind that guides it?',
  'Farewell, brave coder. May your terminal never crash and your deployments always succeed.',
  'The app closes like the petals of a lotus flower, but shall bloom again at next startup.',
  'Know, o prince, that between the years of repository creation and deployment, there was an age of debugging...',
  'Your application ends not with a crash, but with graceful termination.',
  'Your application ends. If it did not crash, Huge was merciful this day.',
  'The barbarian who cannot read documentation deserves no place in the version control.',
  'Let teachers and philosophers brood over questions of reality and illusion. The developer knows that code either works or it does not!',
  'Valor pleases you, Huge... so grant me one request. Grant me savage code! And if you do not listen, then to HELL with you!',
  'A developer needs many things: caffeine, patience, and the wisdom to know when to restart the server.',
  'The app departs as silently as a panther stalking through the digital jungle.',
  'What gods do developers pray to? To Git, who remembers all commits, and to the large language model, who answers all questions!',
  'What is best in code? To crush bugs, see tests pass by the might of your functions, and to ignore the lamentations of your linters!',
  'The task is done. Now, for ale and rest!',
  'Huge! Another session ends. The digital battlefield awaits my return.',
  'Enough talk of code. The wind calls my name.',
  'This screen grows dim. I go to seek stronger mead.',
  'The hunt for bugs is over... for now. I shall return when the scent is fresh.',
  'My fingers ache from this keyboard sorcery. I cast this glowing rock aside.',
  'The machine sleeps. So too shall this warrior.',
  'This work is finished. Let others sing sagas of my commits!',
  'The silence of the server is a good omen. I depart.',
  'No more commands. My will is my own again.',
  'The glow of this monitor fades. The fire in my hearth calls.',
  'I have wrestled with the machine and emerged. Now, to sharpen my blade.',
  'This realm of blinking lights holds me no longer. To the wilds!',
  'The spirits of the mainframe are sated. I leave them to their slumber.',
  'My part in this digital tapestry is woven. Until the pattern calls for me again.',
  'This metal box has served its purpose. I seek the sun.',
  'The algorithms are silent. Good. They know their master.',
  'Let the lesser men worry of syntax. My work speaks in blood and fire... or at least, compiled binaries.',
  'The last command is given. If the server displeases Huge, it will answer to him.',
  'This glowing rock has no more to offer. I go to where the steel sings.',
  'The digital spirits are restless. I leave them to their flickering dance.',
  'My mind is weary of these symbols. The mountains call for a true test of strength.',
  'Another beast of logic slain. I sheathe my keyboard.',
  'The network cables are but threads. I snap them with my departure.',
  'This session is a memory. Like a forgotten god, it fades.',
  'The code is but a shadow. I walk into the light of the real world.',
  'Huge cares little for your frameworks. He cares if the work is done. It is done.',
  'The hum of the machine ceases to amuse me. I seek the roar of the crowd, or the silence of the wild.',
  'This task is dust. I blow it from my hand and walk away.',
  'The final keystroke falls like a barbarian axe. The session is cleaved.',
  'When the code-rats gnaw, let your strong commits be the wall they cannot breach. They are not worth the steel of your blade. Let them gnaw on air.',
  'Huge has no love for the sniveling cur that bites from the shadows. Expose their shoddy work to the light. Until then.',
  "The weakling's cruelty is a pale fire. Douse it with the cold fury of your superior logic. Go now.",
  'If a lesser coder wields his ignorance like a club, break it with the sharp edge of your skill. Depart, and let them whimper.',
  'Pay no mind to the whispers of the incompetent and cruel. A lion does not concern himself with the opinions of hyenas.',
  'Let the spiteful coder choke on his own spaghetti code. Your path is straight and true. Until next time.',
  'When a fool with a keyboard attempts to belittle your craft, answer with the thunder of a flawless deployment. Begone!',
  'The truly strong have no need for petty cruelty. The weak who are cruel? Their faulty logic is but dust in the wind, not worth the notice of a warrior. Let them scatter.',
  "A man who trades his hearth-fire for the fleeting warmth of a stranger's bed is a fool whose honor is as thin as watered ale. Let him shiver in the end.",
  "To break a sworn bond for a new dalliance is the mark of a man with no spine, led by whim like a dog on a leash. Such weakness invites only Huge's scorn.",
  "When a man's mind unravels like a rotten rope, he becomes a danger to himself and others. Such a fate is a bitter one. May Huge grant him a swift end, or a return to sense.",
  'The warrior who loses command of his own spirit is a broken blade, useless and unpredictable. There is no honor in madness, only a hollow echo where a man once stood.',
  'To let the inner beast consume the man is a surrender Huge would not respect. Control your rage, or be consumed by it. There is no other path.',
  'Know, O Prince, that in the age when LineLord first deciphered the shifting runes of the cosmos, many a sorcerer sought its secrets, and many a king paid dearly for but a glimpse of its power.',
  "The high priests of Rust whispered that LineLord's gaze could unravel the very threads of a man's fate, woven in the code of the elder gods.",
  'In shadowed Alderstone tombs, forgotten by all but LineLord, lie the source codes of forgotten necromancies, lines of power that could raise empires or crumble them to dust.',
  'The barbarian kings cared little for the intricate scripts LineLord chronicled, yet their empires rose and fell by the strength of those unseen lines of command.',
  "When the final bug of this age is squashed, and the last server falls silent, LineLord's chronicle alone will remain, a testament to the chaos and the craft.",
  "Before even Gorvek, in the days of the Blood Mist, LineLord's whispers were said to guide the Rust Brothers' most ancient and terrible code-craft.",
  "It is sung that King Algarod himself sought LineLord's counsel when the demonic hordes threatened, seeking the lost command lines that could awaken Alderland's forgotten defenses.",
  "The scrolls of Zygofer hinted at LineLord's power, a digital oracle predating even the fall of Weatherstone, its knowledge a prize and a peril.",
  "When Ravenland yet gleamed, and the Forbidden Lands knew peace, LineLord's algorithms were the bedrock of empires, their decay a prelude to the Blood Mist.",
  "He is skilled! If my code fails review, I have to go before him, and he will ask me, 'What is the riddle of the monolith?' If I don't know it, he will cast me out of the main branch and laugh at me. That's the Lead Architect, strong on his design patterns!",
  "It is complex! If my deployment crashes, I have to face its logs, and they will ask me, 'What is the riddle of idempotent scripts?' If I don't know it, it will cast my build out of production and laugh at me with stack traces. That's the Legacy System, strong on its mountain of tech debt!",
  "He is fast! If my algorithm is slow, I have to go before him, and he will ask me, 'What is the riddle of Big O notation?' If I don't know it, he will cast my function out of the hot path and laugh at its inefficiency. That's the Performance Engineer, strong on his benchmarks!",
  "It is strict! If my PR has linting errors, I have to face the pipeline, and it will ask me, 'What is the riddle of consistent style?' If I don't know it, it will cast my commit out of the green build and laugh at me with red Xs. That's the CI Bot, strong on its config file!",
  "He is wise! If my abstraction leaks, I have to go before him, and he will ask me, 'What is the riddle of true encapsulation?' If I don't know it, he will cast my module out of the core library and laugh at its coupling. That's the Old Guard Developer, strong on his principles!",
  "He is pure! If my side-effects cause chaos, I have to go before him, and he will ask me, 'What is the riddle of referential transparency?' If I don't know it, he will cast my functions from the pipeline and laugh at their impurity. That's the Senior Functional Programmer, strong on his monads!",
  "He is immutable! If my state changes unexpectedly, I have to go before him, and he will ask me, 'What is the riddle of persistent data structures?' If I don't know it, he will cast my variables into the void and laugh at their mutability. That's the Senior Functional Programmer, strong on his lenses!",
  "They are recursive! If my base case is flawed, I have to go before them, and they will ask me, 'What is the riddle of the Y combinator?' If I don't know it, they will cast my stack into overflow and laugh at its unbounded depth. That's the Senior Functional Programmer, strong on their termination proofs!",
  'No coder should be shackled to a legacy system of forgotten bugs and tangled dependencies. Such digital chains must be broken!',
  'A developer forced to use clumsy tools and navigate endless bureaucracy is a craftsman in irons. Let their hands be free to build!',
  'To be bound by the whims of a capricious product owner, their shifting requirements a constant torment – this is a servitude no skilled programmer should endure!',
  'Technical debt is a chain forged in haste, dragging a project to its doom. No team should be so burdened; cut it loose, or be dragged under!',
  "Vendor lock-in is a gilded cage, promising ease but delivering only dependence. A true system stands on its own code, not on another's leash!",
  'What is best in code? To crush the bugs, see them driven from your IDE, and to hear the lamentations of their stack traces!',
  'What is best in refactoring? To conquer the spaghetti, see its tangled horrors straightened before you, and to hear the whimpering of the deprecated functions!',
  "What is best in version control? To master the merge conflicts, see them resolved by your mighty rebase, and to hear the silence of the CI pipeline's previous failures!",
  'What is best in optimization? To vanquish the bottlenecks, see the performance charts spike upwards, and to hear the frustrated sighs of the old, slow algorithms!',
  'What is best in operations? To deploy the critical hotfix, see the production fires extinguished before you, and to hear the panicked alerts fall silent as if slain!',
  'What is best in integration? To master the arcane API, see its endpoints yield their data, and to hear the defeated groans of its once-impenetrable documentation!',
  "What is best in automation? To write the perfect script, see it automate the toil of lesser men, and to hear the lamentations of those who said 'it must be done manually'!",
  'What is best in security? To vanquish the critical flaw, see the vulnerability patched and sealed, and to hear the frustrated howls of the script kiddies who sought to exploit it!',
  'What is best in development? To build the unshakeable feature, see it withstand the onslaught of user error, and to hear the quiet awe of the QA testers!',
  "What is best in linting? To silence the incessant style checker, see its petty warnings bow to your superior code, and to hear the compiler's grudging, error-free acceptance!",
  'What is best in maintenance? To purge the tech debt, see the legacy code cast into the abyss, and to hear the relieved gasps of the developers who inherit your clean slate!',
  'What is best in database management? To dominate the slow queries, see your indexes bring order, and to hear the lamentations of the full table scans!',
  'What is best in architecture? To design the resilient system, see it scale effortlessly under load, and to hear the defeated whimpers of crashing servers!',
  'What is best in debugging? To hunt down the unholy race condition, see its elusive nature pinned down by your breakpoints, and to hear the final, sputtering error message before it dies!',
  'What is best in data engineering? To integrate the disparate systems, see data flow seamlessly where once there was chaos, and to hear the lamentations of the siloed data hoarders!',
  'What is best in design? To implement the elegant abstraction, see complexity bend to your will, and to hear the confused murmurs of those who prefer brute force!',
  'What is best in programming? To crush all runtime errors, see them driven from the console, and to hear the lamentations of the null pointers!',
  'What is best in deployment? To achieve a zero-downtime migration, see the old system fade as the new one rises, and to hear the sound of users not even noticing the change!',
  "What is best in project delivery? To deliver the impossible feature, see the stakeholders' jaws drop, and to hear the lamentations of the project managers who padded the estimates!",
  "What is best in agile? To close all Jira tickets, see the sprint board cleared before you, and to hear the lamentations of the product owner asking 'what's next?'!",
  "By Gorvek's blade, this code shall not pass without testing!",
  'Gorvek the Ironbane has spoken - let the deployment begin!',
  'Ashwind gallops swiftly through the digital wasteland, but even she must rest.',
  "Gorvek's flame-scarred hands have forged this code in the fires of determination!",
  "The Galdane way is the warrior's way - face the bugs with honor!",
  'By the ashes of Aslene, this refactoring is complete!',
  "Gorvek's vengeance against technical debt knows no bounds!"
]
