// Generated by `bun run sync-descent` from the Gallowmark canon (dist/lore.json).
// Do not edit here: change the canon in Gallowmark, then run the sync again.
// Canon generated 2026-10-06.

export type Pool =
  | 'arrive-quays'
  | 'arrive-streets'
  | 'arrive-vaults'
  | 'arrive-hall'
  | 'tide-turning'
  | 'tide-flood'
  | 'tide-ebb'
  | 'tide-low'
  | 'gift'
  | 'tithe'
  | 'naming'
  | 'advice'
  | 'haggle'
  | 'trade'
  | 'salt-pile'
  | 'unasked'
  | 'drain'
  | 'death'
  | 'escape'
  | 'shore'
  | 'jarn'
export type CreatureId =
  | 'pickers'
  | 'firstcloaks'
  | 'the-barred'
  | 'the-unasked'
  | 'notchers'
  | 'the-drawn'
  | 'the-standing'

export const pools: Record<Pool, readonly string[]> = {
  'arrive-quays': [
    'Bones in a cloak the colour of the floor. The order lost men here. The order does not say when.',
    'The silt is grey. Taste it. That is not sand.',
    'Your lamp burns grey. It will burn grey all the way down.',
  ],
  'arrive-streets': [
    'Every door is barred. Look at the scratches. They are on the outside.',
    'Somebody lived down here. Look at the bones in the gutter. Somebody ate.',
    'The doors were barred against something. The sea was only what came first.',
  ],
  'arrive-vaults': [
    'A shelf of ledgers. The last ones count days, not lines. The hand gets worse.',
    'Notches in the salt. Nine to a row. Nobody here is short of time.',
    'Water stands in the air above the cistern. Somebody told it to stop.',
  ],
  'arrive-hall': [
    'The grey stands in the hall like milk in a bowl. It was here first.',
    "The king's crown is warm. Something under the floor is breathing against it.",
    'There is someone standing in the drain. He has been standing there a long time.',
  ],
  'tide-turning': [
    'The flood is turning. The water is coming back up the steps. So is everything in it.',
  ],
  'tide-flood': [
    'Flood. The grey sinks under the water and waits. You have a while.',
  ],
  'tide-ebb': [
    'The water is going out again. Watch the grey. It rises when the sea leaves.',
  ],
  'tide-low': ['Low water. Breathe now, while it is still your air.'],
  gift: [
    'A blade that cuts anything. I did not say what it will cut first.',
    'Refuse, then. I will offer it to the next one. There is always a next one.',
    'Take it. It is better than anything Barr sells. Ask yourself what I sell.',
    'This lamp will never burn grey. I took the grey out of it. I put it somewhere.',
  ],
  tithe: [
    'I am sorry. A tenth, for the fort. It is the same tenth it was yesterday.',
    'Thank you for coming up. The order thanks you. The order would like a tenth.',
    'You may keep the rest. You may always keep the rest. That is how it works.',
  ],
  naming: [
    'Do not ask why. Ask what.',
    'Ruun writes the name in the wet sand. The tide takes it. You do not forget it.',
    'Things that have names can be held. Things that do not, hold you.',
  ],
  advice: [
    'Doors. Do not open them. Not the barred ones.',
    'I went down to the hall once. The crown was warm. I did not go back.',
    'Lamp first. Then knife. In the dark the knife is nothing.',
    'Low water is not safe. It only looks it.',
    'The ropes in the vaults. Cut. Never hold.',
  ],
  haggle: [
    'Forty marks. Forty. Marks.',
    'Mail. The dye is out. Do not ask whose.',
    'That weighs what it weighs. A third.',
  ],
  trade: [
    'Everything I tell you is true. That is why it costs.',
    'I do not want your coin. I want something you do not know you have.',
    'The grey down there is the grey I live beside. It is not two greys. It never was.',
  ],
  'salt-pile': [
    'The sea gave you back. Somebody on the shingle did not wake this morning.',
    'You lay it on the salt-pile. The sea takes the smell of it. Nobody says what it buys.',
  ],
  unasked: [
    'Nobody will ask you what you ate. That is the custom.',
    'You meant it once too often. You are hungry now, and you know what for.',
  ],
  drain: [
    'Do not count my days. The book does that.',
    'Take the book. Go up. I hold.',
    'The stream stops when I say stop. I have not said go.',
  ],
  death: [
    'Another line in the ledger. Short.',
    'I offered. You took. You heard gift.',
    'The grey took you. It takes what it would have used.',
    'You die. Shall the ledger name what you carried?',
  ],
  escape: [
    'Out through the roof with the ledger under your arm. Behind you a man is still holding a river.',
    'You came up. He did not. The book has both your lines now.',
  ],
  shore: [
    'The Linelord draws a line in the sand.',
    'The sea takes the line.',
    "Your line, across Jarn's.",
  ],
  jarn: ['Did you mean to?'],
}

export const opening: readonly string[] = [
  'The sea is going out. You think it is leaving.',
  'Under Kell a king is still reading, and the grey the north remembers has gone home.',
  'Bring me the ledger and I will show you the roof.',
  'I will take one thing for it: the belief that the grey is behind you.',
  'Low water. That is when it breathes.',
]

export const creatures: Record<CreatureId, { name: string; summary: string }> =
  {
    pickers: {
      name: 'The Pickers',
      summary:
        'Coast folk who went down into Kell before you for what they could carry; the ones still down there have decided you are what they can carry.',
    },
    firstcloaks: {
      name: 'The Firstcloaks',
      summary:
        "The order's first men, who guarded the drowned quays of Kell in the grey and never came up; still on duty, still polite, still collecting.",
    },
    'the-barred': {
      name: 'The Barred',
      summary:
        'The drowned of Kell who are still holding their doors shut from the inside; harmless until you open one, and then it is not them you have to worry about.',
    },
    'the-unasked': {
      name: 'The Unasked',
      summary:
        'The people of Kell who lived through the grey in their barred houses under the sea; nobody asked them what they ate, and they can smell hunger on you.',
    },
    notchers: {
      name: 'Notchers',
      summary:
        'Thin grey shapes in the Brinevaults that cut one notch in the wall for every moment you stand in their sight; at nine, a rope finds your neck.',
    },
    'the-drawn': {
      name: 'The Drawn',
      summary:
        'The hanged, with the rope still on, pulled through the Brinevaults toward the iron hall by a rope drawn tight from the other end; they do not fight you, they take you with them.',
    },
    'the-standing': {
      name: 'The Standing',
      summary:
        'The grey in the iron hall, standing still like milk in a bowl and rising when the sea goes out; it does not hurt you, it takes things from you.',
    },
  }
