/**
 * Pull the quote pools from the Gallowmark canon into this repository.
 *
 *   bun run sync-lore                 # reads ../../gallowmark/dist/lore.json if it is
 *                                     # there, else fetches it with the GitHub CLI
 *   bun run sync-lore path/lore.json  # reads that file
 *
 * Writes src/adapters/opentui/resources/gallowmarkQuotes.ts. The farewell quotes
 * and the analysis messages come from there; nothing here is edited by hand.
 * LineLord itself makes no network call: this is a development step, and the
 * generated file is committed.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadLore, ROOT } from './loreSource'

const OUT = join(ROOT, 'src/adapters/opentui/resources/gallowmarkQuotes.ts')
const PROJECT = 'linelord'
const POOLS = [
  'farewell',
  'initializing',
  'scanning',
  'analyzing',
  'complete',
] as const

const lore = loadLore(process.argv[2])
const pools: Record<(typeof POOLS)[number], string[]> = {
  farewell: [],
  initializing: [],
  scanning: [],
  analyzing: [],
  complete: [],
}
let taken = 0
for (const q of lore.quotes) {
  if (!q.usedIn.includes(PROJECT) || q.status === 'retired') continue
  if (!(q.pool in pools)) {
    throw new Error(
      `quote ${q.id} is in pool '${q.pool}', which LineLord has no use for`,
    )
  }
  pools[q.pool as (typeof POOLS)[number]].push(q.text)
  taken++
}
for (const pool of POOLS) {
  if (pools[pool].length === 0)
    throw new Error(`pool '${pool}' is empty in the canon`)
}

const lines = [
  '// Generated by `bun run sync-lore` from the Gallowmark canon (dist/lore.json).',
  '// Do not edit here: add or change a quote in Gallowmark, then run the sync again.',
  `// Canon generated ${lore.generatedAt}; ${taken} quotes for ${PROJECT}.`,
  '',
  `export type GallowmarkPool = ${POOLS.map((p) => `'${p}'`).join(' | ')}`,
  '',
  'export const gallowmarkQuotes: Record<GallowmarkPool, readonly string[]> = {',
]
for (const pool of POOLS) {
  lines.push(`  ${pool}: [`)
  for (const text of pools[pool]) lines.push(`    ${JSON.stringify(text)},`)
  lines.push('  ],')
}
lines.push('}', '')
writeFileSync(OUT, lines.join('\n'))

const fmt = Bun.spawnSync(['bunx', 'biome', 'format', '--write', OUT], {
  stdout: 'pipe',
  stderr: 'pipe',
})
if (fmt.exitCode !== 0)
  throw new Error(fmt.stderr?.toString() ?? 'biome format failed')
console.log(
  `wrote ${OUT}: ${POOLS.map((p) => `${p} ${pools[p].length}`).join(', ')}`,
)
