/**
 * Pull the quote pools from the Gallowmark canon into this repository.
 *
 *   bun run sync-lore                 # reads ../../gallowmark/dist/lore.json if it is
 *                                     # there, else fetches it with the GitHub CLI
 *   bun run sync-lore path/lore.json  # reads that file
 *
 * Writes src/adapters/ink/resources/gallowmarkQuotes.ts. The farewell quotes
 * and the analysis messages come from there; nothing here is edited by hand.
 * LineLord itself makes no network call: this is a development step, and the
 * generated file is committed.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'src/adapters/ink/resources/gallowmarkQuotes.ts')
const SIBLING = join(ROOT, '../../gallowmark/dist/lore.json')
const PROJECT = 'linelord'
const POOLS = [
  'farewell',
  'initializing',
  'scanning',
  'analyzing',
  'complete',
] as const

interface Quote {
  id: string
  text: string
  speaker: string | null
  pool: string
  usedIn: string[]
  status: 'canon' | 'draft' | 'retired'
  tags: string[]
}

function loadLore(arg: string | undefined): {
  generatedAt: string
  quotes: Quote[]
} {
  if (arg) return JSON.parse(readFileSync(arg, 'utf8'))
  if (existsSync(SIBLING)) return JSON.parse(readFileSync(SIBLING, 'utf8'))
  const gh = Bun.spawnSync(
    [
      'gh',
      'api',
      'repos/MarkusAugust/gallowmark/contents/dist/lore.json',
      '-H',
      'Accept: application/vnd.github.raw',
    ],
    { stdout: 'pipe', stderr: 'pipe' },
  )
  if (gh.exitCode !== 0) {
    throw new Error(
      `no lore.json given, none at ${SIBLING}, and gh failed:\n${gh.stderr?.toString() ?? ''}`,
    )
  }
  return JSON.parse(gh.stdout.toString())
}

const lore = loadLore(process.argv[2])
const pools: Record<(typeof POOLS)[number], string[]> = {
  farewell: [],
  initializing: [],
  scanning: [],
  analyzing: [],
  complete: [],
}
let taken = 0
for (const q of lore.quotes) {
  if (!q.usedIn.includes(PROJECT) || q.status === 'retired') continue
  if (!(q.pool in pools)) {
    throw new Error(
      `quote ${q.id} is in pool '${q.pool}', which LineLord has no use for`,
    )
  }
  pools[q.pool as (typeof POOLS)[number]].push(q.text)
  taken++
}
for (const pool of POOLS) {
  if (pools[pool].length === 0)
    throw new Error(`pool '${pool}' is empty in the canon`)
}

const lines = [
  '// Generated by `bun run sync-lore` from the Gallowmark canon (dist/lore.json).',
  '// Do not edit here: add or change a quote in Gallowmark, then run the sync again.',
  `// Canon generated ${lore.generatedAt}; ${taken} quotes for ${PROJECT}.`,
  '',
  `export type GallowmarkPool = ${POOLS.map((p) => `'${p}'`).join(' | ')}`,
  '',
  'export const gallowmarkQuotes: Record<GallowmarkPool, readonly string[]> = {',
]
for (const pool of POOLS) {
  lines.push(`  ${pool}: [`)
  for (const text of pools[pool]) lines.push(`    ${JSON.stringify(text)},`)
  lines.push('  ],')
}
lines.push('}', '')
writeFileSync(OUT, lines.join('\n'))

const fmt = Bun.spawnSync(['bunx', 'biome', 'format', '--write', OUT], {
  stdout: 'pipe',
  stderr: 'pipe',
})
if (fmt.exitCode !== 0)
  throw new Error(fmt.stderr?.toString() ?? 'biome format failed')
console.log(
  `wrote ${OUT}: ${POOLS.map((p) => `${p} ${pools[p].length}`).join(', ')}`,
)
