/**
 * Pull the game's lines from the Gallowmark canon into the demo site.
 *
 *   bun run sync-descent                 # the sibling checkout, else the GitHub CLI
 *   bun run sync-descent path/lore.json  # that file
 *
 * Writes site/descent/lore.ts: every quote with `used-in: [descent]`, by pool,
 * Sarn's opening from `stories/the-descent`, the one-line summary of each
 * creature the game uses, and the name, epithet and summary of the holders.
 * Draft quotes are taken, because the game is what the drafts are for;
 * retired ones are not. Nothing in lore.ts is edited by hand.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadLore, ROOT } from './loreSource'

const OUT = join(ROOT, 'site/descent/lore.ts')
const PROJECT = 'descent'
const POOLS = [
  'arrive-quays',
  'arrive-streets',
  'arrive-vaults',
  'arrive-hall',
  'tide-turning',
  'tide-flood',
  'tide-ebb',
  'tide-low',
  'gift',
  'tithe',
  'naming',
  'advice',
  'haggle',
  'trade',
  'salt-pile',
  'unasked',
  'drain',
  'death',
  'escape',
  'shore',
  'jarn',
  'hollin',
  'hollin-yields',
  'grue',
  'grue-yields',
  'sethra',
  'sethra-yields',
  'corve',
  'corve-yields',
  'wrack',
  'title-won',
  'title-lost',
  'linelord-won',
] as const
const CREATURES = [
  'pickers',
  'firstcloaks',
  'the-barred',
  'the-unasked',
  'notchers',
  'the-drawn',
  'the-standing',
] as const
/** The holders of Kell's four depths, and the Linelord above them. */
const HOLDERS = ['hollin', 'grue', 'sethra', 'corve', 'jarn'] as const

const lore = loadLore(process.argv[2])

const pools = Object.fromEntries(POOLS.map((p) => [p, [] as string[]]))
for (const q of lore.quotes) {
  if (!q.usedIn.includes(PROJECT) || q.status === 'retired') continue
  const pool = pools[q.pool]
  if (!pool) {
    throw new Error(
      `quote ${q.id} is in pool '${q.pool}', which the descent has no use for`,
    )
  }
  pool.push(q.text)
}
for (const pool of POOLS) {
  if (pools[pool]?.length === 0)
    throw new Error(`pool '${pool}' is empty in the canon`)
}

const story = lore.entities['the-descent']
if (!story) throw new Error('stories/the-descent is missing from the canon')
const opening = story.body
  .split('\n\n')
  .filter((p) => p.startsWith('*'))
  .map((p) => p.replace(/^\*|\*$/g, '').replace(/\s+/g, ' '))

const creatures = Object.fromEntries(
  CREATURES.map((id) => {
    const e = lore.entities[id]
    if (!e) throw new Error(`creatures/${id} is missing from the canon`)
    return [id, { name: e.name, summary: e.summary }]
  }),
)

const holders = Object.fromEntries(
  HOLDERS.map((id) => {
    const e = lore.entities[id]
    if (!e) throw new Error(`characters/${id} is missing from the canon`)
    if (!e.epithet) throw new Error(`characters/${id} has no epithet`)
    return [id, { name: e.name, epithet: e.epithet, summary: e.summary }]
  }),
)

const lines = [
  '// Generated by `bun run sync-descent` from the Gallowmark canon (dist/lore.json).',
  '// Do not edit here: change the canon in Gallowmark, then run the sync again.',
  `// Canon generated ${lore.generatedAt}.`,
  '',
  `export type Pool = ${POOLS.map((p) => `'${p}'`).join(' | ')}`,
  `export type CreatureId = ${CREATURES.map((c) => `'${c}'`).join(' | ')}`,
  `export type HolderId = ${HOLDERS.map((h) => `'${h}'`).join(' | ')}`,
  '',
  `export const pools: Record<Pool, readonly string[]> = ${JSON.stringify(pools, null, 2)}`,
  '',
  `export const opening: readonly string[] = ${JSON.stringify(opening, null, 2)}`,
  '',
  `export const creatures: Record<CreatureId, { name: string; summary: string }> = ${JSON.stringify(creatures, null, 2)}`,
  '',
  `export const holders: Record<HolderId, { name: string; epithet: string; summary: string }> = ${JSON.stringify(holders, null, 2)}`,
  '',
]
writeFileSync(OUT, lines.join('\n'))

const fmt = Bun.spawnSync(['bunx', 'biome', 'format', '--write', OUT], {
  stdout: 'pipe',
  stderr: 'pipe',
})
if (fmt.exitCode !== 0)
  throw new Error(fmt.stderr?.toString() ?? 'biome format failed')
console.log(
  `wrote ${OUT}: ${POOLS.map((p) => `${p} ${pools[p]?.length}`).join(', ')}`,
)
